id = "3dbbafa0-5f1d-44e0-8993-0d3207aae20f"
title = "Fyra separata budgetsektioner för projektet"
started_at = 1778606555
ended_at = 1778610875
participants = []
project_id = "1d27b3d1-197b-412c-a5be-01f8ccafe9c4"
primary_language = "swe"
